# Generated by Django 5.2.8 on 2026-03-06 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='barangay',
            name='population',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
