# Generated by Django 6.0.2 on 2026-03-07 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_barangay_population'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='transaction_type',
            field=models.CharField(default='G2C - Government to Citizen', max_length=100),
        ),
        migrations.AddField(
            model_name='program',
            name='who_may_avail',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='name',
            field=models.CharField(max_length=300, unique=True),
        ),
        migrations.CreateModel(
            name='ProgramRequiredDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(max_length=300)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('is_required', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_documents', to='core.program')),
            ],
            options={
                'ordering': ['category', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='application_documents/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('missing', 'Missing')], default='pending', max_length=20)),
                ('admin_note', models.CharField(blank=True, max_length=300)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_documents', to='core.assistancerequest')),
                ('required_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.programrequireddocument')),
            ],
            options={
                'ordering': ['required_document__order'],
            },
        ),
    ]
