# Generated by Django 6.0.2 on 2026-03-07 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_program_transaction_type_program_who_may_avail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistancerequest',
            name='selected_category',
            field=models.CharField(blank=True, help_text='Sub-category chosen by applicant (e.g. Sa Medikal, Senior Citizen)', max_length=200),
        ),
    ]
