# Generated by Django 5.2.8 on 2026-03-08 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_assistancerequest_selected_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beneficiary',
            name='program',
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Verification'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
