# Generated by Django 5.2.8 on 2026-03-08 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_beneficiary_program_alter_beneficiary_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='admin_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
