# Generated by Django 5.2.8 on 2026-03-26 08:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_beneficiary_admin_note'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='disability_status',
            field=models.BooleanField(default=False, help_text='Does the beneficiary have a disability?'),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='employment_status',
            field=models.CharField(blank=True, choices=[('employed', 'Employed'), ('unemployed', 'Unemployed'), ('self_employed', 'Self-Employed'), ('retired', 'Retired')], default='unemployed', max_length=20),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='last_assistance_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='vulnerability_level',
            field=models.CharField(default='low', help_text='Auto: low/medium/high/critical', max_length=10),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='vulnerability_score',
            field=models.FloatField(default=0, help_text='Auto-computed 0-100 score'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('staff', 'Staff'), ('user', 'User')], default='user', max_length=10),
        ),
        migrations.CreateModel(
            name='StaffActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('approve', 'Approved Request'), ('reject', 'Rejected Request'), ('review', 'Reviewed Request'), ('view', 'Viewed Record'), ('update', 'Updated Status')], max_length=20)),
                ('target_type', models.CharField(help_text='e.g. AssistanceRequest, Beneficiary', max_length=50)),
                ('target_id', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_programs', models.ManyToManyField(blank=True, related_name='assigned_staff', to='core.program')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
