# Generated by Django 6.0.3 on 2026-05-08 05:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_beneficiary_disability_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('new_request', 'New Assistance Request'), ('request_approved', 'Request Approved'), ('request_rejected', 'Request Rejected'), ('schedule_assigned', 'Schedule Assigned'), ('schedule_reminder', 'Schedule Reminder'), ('schedule_missed', 'Missed Appointment'), ('claim_completed', 'Claim Completed'), ('reschedule_request', 'Reschedule Requested'), ('pending_approval', 'Pending Approval'), ('general', 'General')], default='general', max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('related_url', models.CharField(blank=True, max_length=500)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_date', models.DateField(blank=True, null=True)),
                ('time_slot', models.CharField(blank=True, choices=[('08:00', '8:00 AM – 9:00 AM'), ('09:00', '9:00 AM – 10:00 AM'), ('10:00', '10:00 AM – 11:00 AM'), ('11:00', '11:00 AM – 12:00 PM'), ('13:00', '1:00 PM – 2:00 PM'), ('14:00', '2:00 PM – 3:00 PM'), ('15:00', '3:00 PM – 4:00 PM'), ('16:00', '4:00 PM – 5:00 PM')], help_text='Hour block (HH:MM)', max_length=5)),
                ('claim_location', models.CharField(default='CSWDO Office, Tayabas City', max_length=300)),
                ('max_per_slot', models.PositiveIntegerField(default=10, help_text='Max beneficiaries per slot')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('scheduled', 'Scheduled'), ('claimed', 'Claimed'), ('completed', 'Completed'), ('missed', 'Missed'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('reschedule_count', models.PositiveIntegerField(default=0)),
                ('reschedule_requested', models.BooleanField(default=False)),
                ('reschedule_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_schedules', to=settings.AUTH_USER_MODEL)),
                ('assistance_request', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='core.assistancerequest')),
                ('barangay', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='core.barangay')),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='core.beneficiary')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_schedules', to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='core.program')),
            ],
            options={
                'verbose_name': 'Scheduled Transaction',
                'verbose_name_plural': 'Scheduled Transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_value', models.DecimalField(decimal_places=2, default=0, help_text='Monetary value of assistance received (if applicable)', max_digits=12)),
                ('claim_date', models.DateField(blank=True, null=True)),
                ('transaction_status', models.CharField(default='completed', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('document_attachment', models.FileField(blank=True, null=True, upload_to='service_history_docs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_records', to=settings.AUTH_USER_MODEL)),
                ('assistance_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history', to='core.assistancerequest')),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_history', to='core.beneficiary')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_history', to='core.program')),
                ('scheduled_transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history', to='core.scheduledtransaction')),
            ],
            options={
                'verbose_name': 'Service History',
                'verbose_name_plural': 'Service Histories',
                'ordering': ['-created_at'],
            },
        ),
    ]
